gcloud ml-engine jobs submit training minst_cnn_63 \
	--job-dir gs://federer-hyj2721-kaggle-minst/trainer/output/ \
	--module-name trainer.task \
	--package-path trainer/ \
	--region us-west1 \
	--config=cloudml-gpu.yaml \
	-- \
    --layer_nodes=32_64 \
    --train_rounds=400 \
    --load_model_name=32_64__200 \
    --using_gpu=True